version: '3'
services:
  my-node-app:
    image: node:latest
    working_dir: /app
    volumes:
      - /Users/rahuljangir/Git/mern-ecom:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
