services:
  react:
    build: .
    container_name: ecom
    ports:
      - 3000:3000
    depends_on:
      - mongoDb
    networks:
      - mynetwork
    
  mongoDb:
    image: "mongo"
    container_name: ecom-db
    ports:
      - 27017:27017
    networks:
      - mynetwork

networks:
  mynetwork:
